services:

  postgres:
    # We use pgvector/pgvector instead of standard postgres to support vector embeddings.
    # We will use this locally, but keep the code modular to switch to Pinecone in production.
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U raguser -d ragdb" ]
      interval: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ minio_data:/data ]

  ingest:
    build:
      context: .
      dockerfile: ./services/ingest/Dockerfile
    ports: [ "8001:8000" ]
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }

  celery_worker:
    build:
      context: .
      dockerfile: ./services/ingest/Dockerfile
    command: celery -A shared.queue.celery_app worker --loglevel=info
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }

  search:
    build: ./services/search
    ports: [ "8002:8000" ]
    env_file: .env
    depends_on:
      postgres: { condition: service_healthy }

  qpaper:
    build: ./services/qpaper
    ports: [ "8003:8000" ]
    env_file: .env

  viva:
    build: ./services/viva
    ports: [ "8004:8000" ]
    env_file: .env

  gateway:
    build: ./services/gateway
    ports: [ "8000:8000" ]
    env_file: .env

  frontend:
    build: ./frontend
    ports: [ "3000:3000" ]

volumes:
  pg_data:
  minio_data:
