"""initial schema baseline

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-29

Baseline migration. Reproduces the full current schema from the shared ORM
metadata (every table in services/shared/db/models.py), enables the pgvector
extension, and creates the HNSW ANN index used for cosine similarity search.

This replaces the old app-startup ``create_all`` + ``CREATE EXTENSION`` +
ad-hoc ``ALTER TABLE`` path. Future schema changes use ordinary autogenerated
revisions on top of this baseline.
"""

import sys
from pathlib import Path

from alembic import op

# Ensure the shared package is importable when Alembic loads this revision.
SHARED_DIR = Path(__file__).resolve().parents[3]
if str(SHARED_DIR) not in sys.path:
    sys.path.insert(0, str(SHARED_DIR))

from db.models import Base  # noqa: E402

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # pgvector must exist before the Vector column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Create every table defined on the shared metadata (idempotent).
    Base.metadata.create_all(bind=bind)
    # Approximate-nearest-neighbour index for cosine similarity (matches
    # DocumentChunk.embedding.cosine_distance() used across the services).
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    bind = op.get_bind()
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw")
    Base.metadata.drop_all(bind=bind)
